### ISSUE TITLE
hw3_release Extra Credit: Stitching Multiple Images?

### ISSUE THREAD

**Issue by lgqfhwy** [mikucy/CS131#1]
Hello, I am a beginner. In hw3_release Extra Credit: Stitching Multiple Images, I don't know how to do.
The problem said given a sequence of m images, then stitch an ordered chain of images. I want to take the first and second images then stitch together, formed a new images, then stitch together the third images. But it is too complex and maybe have some simple ways.
I notice that you haven't do this problem, if you have any idea, please complete the code. I am a beginner, it is too hard for me. Thank you so much.

**Comment by mikucy** [comment]
@lgqfhwy Hello, thanks for your issue, I'm a beginner too. The code has been uploaded, you can check it.

The basic idea is to perform as the hint says:
* First compute the transform matrix for every `Image_i+1` to `Image_i`
* Then select a image to be the `reference image` (here I choose image2), compute the transform matrix for other image to the `reference image`,  **remember the transform matrix can be multiplied in chain (i.e., H12.dot(H23) transforms `image3` to `image1`), also it can be multiplied reversely (i.e., inv(H12) transforms `image1` to `image2`)**
* Finally merge the warped images together, I am not sure how to do it perfectly as well so I just copy the former part of the code, but it looks not so bad :)

Notice that you are also Chinese, if you have more questions, contact me at qq:419714107
Best regards.
